# Generated by Django 4.2.14 on 2024-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_customuser_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
