# Generated by Django 4.2.14 on 2024-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=255)),
                ('posicion', models.CharField(max_length=50)),
            ],
        ),
    ]
